# Probability Distributions

## Probability Distributions & Expected Values

### Question 1
> 3.25 ) From a box containing 4 dimes and 2 nickels, 3 coins are selected at random without replacement. Find the probability distribution for the total T of the 3 coins. Express the probability distribution graphically as a probability histogram.

> Possible outcomes (coin combinations) and their totals:
> - 3 dimes = 30 cents
> - 2 dimes + 1 nickel = 25 cents
> - 1 dime + 2 nickels = 20 cents
> - 3 nickels = 15 cents

In [1]:
# Total values and their probabilities
total_values <- c(30, 25, 20, 15)
probabilities <- c(0.2, 0.6, 0.2, 0)

In [2]:
# Create a data frame
data <- data.frame(total_values, probabilities)

In [3]:
# Plot the probability histogram
library(ggplot2)

ggplot(data, aes(x = factor(total_values), y = probabilities)) +
  geom_bar(stat = "identity", fill = "skyblue", color = "black") +
  labs(title = "Probability Distribution of Total Value of Coins",
       x = "Total Value (cents)",
       y = "Probability") +
  theme_minimal()

### Question 2
> Based on extensive testing, it is determined by the manufacturer of a washing machine that the time Y (in years) before a major repair is required is characterized by the probability density function
> - (a)Critics would certainly consider the product a bargain if it is unlikely to require a major repair before the sixth year. Comment on this by determining P(Y>6).
> - (b) What is the probability that a major problem occurs in the first year?


In [4]:
# Calculate the probability
probability <- exp(-3/2)
print(probability)

[1] 0.2231302


In [5]:
# Calculate the probability
probability <- 1 - exp(-1/4)
print(probability)

[1] 0.2211992


### Question 4 

Suppose that X and Y have the following joint probability function:
>- (a)Find the expected value of g(X,Y)=XY^2.
>- (b)Find μX and μY .


Possible Values of (X, Y)
- (1,2) with probability 0.10
- (1,4) with probability 0.15
- (3,2) with probability 0.20
- (3,4) with probability 0.30
- (5,2) with probability 0.10
- (5,4) with probability 0.15

Compute XY^2 for each pair (X,Y):
- g(1,2)=1⋅2^2 =4
- g(1,4)=1⋅4^2 =16
- g(3,2)=3⋅2^2 =12
- g(3,4)=3⋅4^2 =48
- g(5,2)=5⋅2^2 =20
- g(5,4)=5⋅4^2 =80

Expected Value of g(X,Y)=XY^2 is E[XY^2]=34.60.:
- E[XY^2]=4⋅0.10+16⋅0.15+12⋅0.20+48⋅0.30+20⋅0.10+80⋅0.15
- E[XY^2]=0.40+2.40+2.40+14.40+2.00+12.00
- E[XY^2]= 33.60

## Discrete Probability Distribution

### Question 1

5.15) It is known that 60% of mice inoculated with a serum are protected from a certain disease. If 5 mice are inoculated, find the probability that

- (a) none contracts the disease.
- (b) fewer than 2 contract the disease.
- (c) more than 3 contract the disease.


In [6]:
# P(X=x) is the binomial probability (discrete probability distribution)
# "In relation to successfully protected from disease"
# n = 5 (5 mice)
# x = 5 (5 successful protected mice trials)
# p = .60 (success protected percentage)
# q = (1-p)= .40 (failed contracted disease percentage)

In [7]:
n <- 5
x <- 5
p <- 0.60

# Calculate the binomial probability
probability <- choose(n, x) * (p^x) * ((1-p)^(n-x))
percentage <- probability * 100
percentage

[1] 7.776

In [8]:
# P(X < 2) = P(X = 0) + P(X = 1) "In relation to contracted disease"
# n = 5 (5 mice)
# x_0 = 0 (0 disease contracted mice trials)
# x_1 = 1 (1 disease contracted mice trials)
# p = .60 (success protected percentage)
# q = (1-p)= .40 (failed disease contracted percentage)

In [9]:
# Number of mice trials
n <- 5
# Probability of contracting the disease
p_contract <- 0.40
# Probability of being protected
p_protected <- 0.60

# Calculate the probabilities
P_X_0 <- choose(n, 0) * (p_contract^0) * (p_protected^5)
P_X_1 <- choose(n, 1) * (p_contract^1) * (p_protected^4)

# Total probability that fewer than 2 mice contract the disease
P_X_less_than_2 <- P_X_0 + P_X_1

# Convert to percentage
P_X_less_than_2_percentage <- P_X_less_than_2 * 100

# Print the result
P_X_less_than_2_percentage

[1] 33.696

In [10]:
# P(X > 3) = P(X = 4) + P(X = 5) "In relation to contracted disease"
# n = 5 (5 mice)
# x_4 = 4 (4 disease contracted mice trials)
# x_5 = 5 (5 disease contracted mice trials)
# p = .60 (success protected percentage)
# q = (1-p)= .40 (failed disease contracted percentage)

In [11]:
# Probability of contracting the disease
p_contract <- 0.40
# Probability of being protected
p_protected <- 0.60

# Calculate the probabilities
P_X_4 <- choose(n, 4) * (p_contract^4) * (p_protected^(n-4))
P_X_5 <- choose(n, 5) * (p_contract^5) * (p_protected^(n-5))

# Total probability that more than 3 mice contract the disease
P_X_more_than_3 <- P_X_4 + P_X_5

# Convert to percentage
P_X_more_than_3_percentage <- P_X_more_than_3 * 100

P_X_more_than_3_percentage

[1] 8.704

### Question 2 

5.63) Find the mean and variance of the random variable X in Exercise 5.58, representing the number of hurricanes per year to hit a certain area of the eastern United States.
>5.58) A certain area of the eastern United States is, on average, hit by 6 hurricanes a year. Find the probability that in a given year that area will be hit by
> - (a) fewer than 4 hurricanes.
> - (b) anywhere from 6 to 8 hurricanes.


Answer: The mean (μ) and variance (σ) are 6. This is especially true (theorem) in a Poisson Distribution.  

### Question 3

6.13) A research scientist reports that mice will live an average of 40 months when their diets are sharply restricted and then enriched with vitamins and proteins. Assuming that the lifetimes of such mice are normally distributed with a standard deviation of 6.3 months, find the probability that a given mouse will live
- (a) more than 32 months.
- (b) less than 28 months.
- (c) between 37 and 49 months.


In [12]:
mu <- 40  # Mean (months)
sigma <- 6.3  # Standard deviation (months)

In [13]:
# P(X > 32 months) = 
lower_bound <- 32

# Calculate the probability using pnorm (normal distribution)
probability <- 1 - pnorm(lower_bound, mean = mu, sd = sigma)

# Print the result
probability

[1] 0.8979294

In [14]:
# P(X < 28 months) = 
upper_bound <- 28  # Given upper bound

# Calculate the probability using pnorm
probability <- pnorm(upper_bound, mean = mu, sd = sigma)

# Print the result
probability

[1] 0.02840551

In [15]:
# P( 37 < X < 49 months) = 
lower_bound <- 37  # Lower bound
upper_bound <- 49  # Upper bound

# Calculate the cumulative probabilities
p_lower <- pnorm(lower_bound, mean = mu, sd = sigma)
p_upper <- pnorm(upper_bound, mean = mu, sd = sigma)

# The probability that the mouse will live between 37 and 49 months
probability <- p_upper - p_lower

# Print the result
probability

[1] 0.6064669

### Question 4

6.33) Statistics released by the National Highway Traffic Safety Administration and the National Safety Council show that on an average weekend night, 1 out of every 10 drivers on the road is drunk. If 400 drivers are randomly checked next Saturday night, what is the probability that the number of drunk drivers will be
- (a) less than 32?
- (b) more than 49?
- (c) at least 35 but less than 47?


In [16]:
# Normal Approximation to the Binomial 

# n = 400 people
# p = prob_drunk_driver = 1 / 10 = .10 
n <- 400
p <- 0.10

# Mean and standard deviation for the normal approximation
mu <- n * p
sigma <- sqrt(n * p * (1 - p))

In [17]:
# P(X < 32) = P(Z > (x + .5)* mu / sigma) 

# Desired value (added continuity correction)
x <- 32 + .5

# Calculate the probability using pnorm
probability <- pnorm(x, mean = mu, sd = sigma)

# Print the result
probability

[1] 0.1056498

In [18]:
# P(X > 49) = P(Z > (x - .5)* mu / sigma) 

# Desired value (added continuity correction)
x <- 49 - .5

# Calculate the probability using pnorm
probability <- 1 - pnorm(x, mean = mu, sd = sigma)

# Print the result
probability

[1] 0.0782902

In [21]:
# P(35 < X < 47) = P(Z < (47 + .5)* mu / sigma) - P(Z < (35 - .5)* mu / sigma) 

# Desired value (added continuity correction)
lower_bound <- 35 - .5 # P(X > 35)
upper_bound <- 47 + .5 # P(X < 47)

# Calculate the probability using pnorm
p_lower <- pnorm(lower_bound, mean = mu, sd = sigma) # P(Z < (35 - .5)* mu / sigma)
p_upper <- pnorm(upper_bound, mean = mu, sd = sigma) #  P(Z < (47 + .5)* mu / sigma)

# The probability the number drunk drivers will be between 35 and 47
probability <- p_upper - p_lower

# Print the result
probability

[1] 0.7146916

### Question 5

6.45) The length of time for one individual to be served at a cafeteria is a random variable having an exponential distribution with a mean of 4 minutes. What is the probability that a person is served in less than 3 minutes on at least 4 of the next 6 days?

In [20]:
# mu (mean) = 4 (min)
# lambda = 1 / mu = 1/4
# time = 3 min
# P(T < 3) = 1 - e^(-lambda * t)
lambda <- .25
time = 3 

# Exponential Distribution (Continuous Probability Distribution)
exp_distribution  <- (1 - exp(-lambda * time))
print(exp_distribution)

[1] 0.5276334


The probability that a person is served in less than 3 minutes is approximately 0.5276 or 52.76%

## Poisson Distribution & Gamma Function

### Poisson 
- Let's answer "What's the probability of 'x' events occurring with the mean of 'lambda'?" 

In [9]:
# help(ppois) # for explanantion of Poission Distribution

In [13]:
# lambda  = mu (mean) = simga (variance) = avg. of occurences 
# x = event occurrences 'random variable'
lambda = 10
desired_occurences = 15

dpois(x= desired_occurences, lambda = lambda)

[1] 0.03471807

- λ = 10 (mean) ; x = 15
P(X = 15) = 〖(λ〗^15*e^λ)/(15!)=  〖(10〗^15*e^(-10))/(15!)=(1000000000000000* 4.5399929762484854e-05)/ (1307674368000) =0.0347180696306841
- P(X = 15) = 3.47181%

### Gamma Function

In [37]:
# help(qgamma)

The function call `pgamma(10, alpha, 1/beta)` computes `P(X≤10)`, which is the probability that a Gamma-distributed random variable X with shape parameter 3 and scale parameter 2.

In [42]:
# Gamma Cumulative Distribution Function at P(X <= 10)
alpha = 3
beta = 2

pgamma(10, alpha, 1/beta) # Cumulative Distribution Function (CDF)
qgamma(.001,alpha, 1/beta) # For note, quantile function

[1] 0.875348

[1] 0.3810668

In [45]:
# computed probability density function (PDF) value for x=10 in a Gamma distribution 
# Given parameters
alpha <- 3
beta <- 2
x <- 10

# Calculate the Gamma PDF value
dgamma(x, shape = alpha, scale = beta)

[1] 0.04211217

Gamma Distribution:
alpha = 3; beta = 2

Gamma Function:
> gamma(alpha) = gamma(3)

> gamma(3) = ∫ [0 ->∞] : {t^(3-1)*exp^(t) dt}

> gamma(3) = 2

Gamma Distribution: 
>f(x) = ( 1/(beta^(alpha)*gamma(alpha))) * x^(alpha - 1) * exp^(-x / beta)

>f(x) = ( 1/(2^(3)*2)) * x^(3 - 1) * exp^(-x / 2)

>f(x) = (1/16) * x^(2) * exp^(-x / 2)

>f(X = 10) = (1/16) * 10^(2) * exp^(-10 / 2)

In [43]:
gamma_distribution <- (1/16) * 10^(2) * exp(-10 / 2)
gamma_distribution

[1] 0.04211217